class_name ComicPlayer
extends CanvasLayer
## Shows a story beat as wide comic panels instead of as a dialogue box over the street.
##
## The panel artwork is generated by `tools/gen_comics.py` and contains no words. The speech
## bubble is drawn here, at runtime, in the game's own UI font: text baked into a PNG cannot
## be restyled, cannot be translated, and is blurry at every scale but the one it was drawn
## at. The bubble's side is authored alongside the art in `data/comics/<id>.json`, so the
## words sit where the panel was composed to leave room for them.
##
## Advancing is the same input as dialogue, and Back skips the whole thing, because a player
## who has read the intro once should never have to read it twice.

signal finished

const DATA_DIR := "res://data/comics/"
const ART_DIR := "res://assets/art/comics/"

## Longest a panel will sit on screen with nobody pressing anything.
##
## Input is the intended way through, but a full-screen thing that ONLY responds to input
## is a hang waiting to happen -- during a cutscene the player may not know it wants a key,
## and an automated run has no hands. This is the floor under that.
const PANEL_DWELL := 7.0

var _panels: Array = []
var _index: int = -1
var _running := false
var _dwell: float = 0.0

var _root: Control
var _art: TextureRect
var _bubble: PanelContainer
var _bubble_col: VBoxContainer
var _speaker: Label
var _text: Label
var _hint: Label

func _ready() -> void:
	layer = 80
	process_mode = Node.PROCESS_MODE_ALWAYS
	_build()
	visible = false

func _build() -> void:
	_root = Control.new()
	_root.set_anchors_preset(Control.PRESET_FULL_RECT)
	_root.mouse_filter = Control.MOUSE_FILTER_STOP
	add_child(_root)

	# Black behind the panel: the art is 3:1 and the screen is not, so there is always
	# letterboxing. Owning it deliberately reads as a comic; leaving the street visible
	# behind it reads as a bug.
	var back := ColorRect.new()
	back.set_anchors_preset(Control.PRESET_FULL_RECT)
	back.color = Color(0.03, 0.03, 0.05)
	_root.add_child(back)

	_art = TextureRect.new()
	_art.set_anchors_preset(Control.PRESET_FULL_RECT)
	_art.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	_art.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	# Nearest, always. This is pixel art and smoothing it turns it to mush.
	_art.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	_root.add_child(_art)

	_bubble = PanelContainer.new()
	_bubble.add_theme_stylebox_override("panel",
		UITheme.panel_style(Color(0.97, 0.96, 0.94), Color(0.08, 0.07, 0.10), 2))
	_root.add_child(_bubble)
	_bubble_col = VBoxContainer.new()
	_bubble_col.add_theme_constant_override("separation", 1)
	_bubble.add_child(_bubble_col)
	_speaker = Label.new()
	UITheme.style_label(_speaker, 9, Color(0.35, 0.20, 0.12), 0)
	_bubble_col.add_child(_speaker)
	_text = Label.new()
	_text.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	UITheme.style_label(_text, 11, Color(0.08, 0.07, 0.10), 0)
	_bubble_col.add_child(_text)

	_hint = Label.new()
	_hint.set_anchors_preset(Control.PRESET_BOTTOM_RIGHT)
	_hint.position = Vector2(-150, -14)
	_hint.size = Vector2(140, 12)
	_hint.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	UITheme.style_label(_hint, 8, UITheme.TEXT_DIM)
	_root.add_child(_hint)

func is_playing() -> bool:
	return _running

## Play a comic by id. Awaited, so a cutscene step can sit on it.
func play(comic_id: String) -> void:
	var panels := _load(comic_id)
	if panels.is_empty():
		push_warning("[ComicPlayer] no panels for '%s'" % comic_id)
		return
	_panels = panels
	_index = -1
	_running = true
	visible = true
	GameManager.set_state(GameManager.State.CUTSCENE)
	_advance()
	while _running:
		# Aborting the cutscene aborts the comic with it, or Back during a scene skips
		# everything except the panels, which is the one part actually on screen.
		if CutsceneManager.is_aborting():
			_running = false
			break
		_dwell -= get_process_delta_time()
		if _dwell <= 0.0:
			_advance()
		await get_tree().process_frame
	visible = false
	finished.emit()

func _load(comic_id: String) -> Array:
	var path := DATA_DIR + comic_id + ".json"
	if not FileAccess.file_exists(path):
		return []
	var f := FileAccess.open(path, FileAccess.READ)
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	if parsed is Dictionary:
		return parsed.get("panels", [])
	return []

func _advance() -> void:
	_index += 1
	if _index >= _panels.size():
		_running = false
		return
	var p: Dictionary = _panels[_index]
	var tex_path: String = ART_DIR + str(p.get("art", "")) + ".png"
	_art.texture = load(tex_path) if ResourceLoader.exists(tex_path) else null

	var who := str(p.get("speaker", ""))
	_speaker.text = who
	_speaker.visible = who != ""
	_text.text = str(p.get("text", ""))
	_hint.text = "Enter  next        Back  skip"
	_dwell = PANEL_DWELL
	_place_bubble(str(p.get("bubble", "left")))

## Put the bubble on the side the panel was composed to leave open.
func _place_bubble(side: String) -> void:
	var vp := _root.size
	var w: float = clampf(vp.x * 0.42, 160.0, 420.0)
	_bubble.custom_minimum_size = Vector2(w, 0)
	_bubble.size = Vector2(w, 0)
	var margin: float = vp.x * 0.05
	var x: float = margin if side == "left" else vp.x - w - margin
	_bubble.position = Vector2(x, vp.y * 0.16)

func _input(event: InputEvent) -> void:
	if not _running:
		return
	if event.is_action_pressed("menu_back") or event.is_action_pressed("pause"):
		_running = false
		get_viewport().set_input_as_handled()
		return
	if event.is_action_pressed("menu_confirm") or event.is_action_pressed("attack_light"):
		AudioManager.play_ui("menu_move")
		_advance()
		get_viewport().set_input_as_handled()
